apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctrl-mqttserver
  namespace: ctrl-apps
  labels:
    app: mqttserver
spec:
  selector:
    matchLabels:
      app: mqttserver
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mqttserver
    spec:
      containers:
        - name: mqttserver
          image: ghcr.io/sg-wireless/mqttserver-dev:2.4.0
          # resources:
          #   requests:
          #     cpu: 200m
          #     memory: 200Mi
          #   limits:
          #     cpu: 200m
          #     memory: 200Mi
          ports:
          - containerPort: 3103
            name: grpc
          - containerPort: 3003
            name: mqttserver
          # command: [ "sh", "-c", "--" ]
          # args: [ "while true; do sleep 30; done;" ]
          env:
            - name: NODE_ENV
              value: "development"
            - name: APP_ENV
              value: "development"
            - name: DOCKER_DEV
              value: "true"
      imagePullSecrets:
        - name: ghcr-login-secret
