---
apiVersion: v1
kind: Service
metadata:
  name: ctrl-mqtt-proxy
  namespace: ctrl-apps
  labels:
    app: mqtt-proxy
spec:
  ports:
    - name: unsecure
      port: 1883
    - name: ws
      port: 3002
  type: ClusterIP
  selector:
    app: mqtt-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: ctrl-mqtt-proxy-lb
  namespace: ctrl-apps
  labels:
    app: mqtt-proxy
spec:
  ports:
    - name: unsecure
      port: 1883
      targetPort: 1883
      protocol: TCP
    - name: ws
      port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    app: mqtt-proxy
  type: LoadBalancer
---
