---
apiVersion: v1
kind: Service
metadata:
  name: ctrl-lorabridge
  namespace: ctrl-apps
  labels:
    app: lorabridge
spec:
  ports:
    - port: 3012
      name: grpc 
    - port: 3015
      name: lorabridge-dev
  type: ClusterIP
  selector:
    app: lorabridge
