---
apiVersion: v1
kind: Service
metadata:
  name: ctrl-management
  namespace: ctrl-apps
  labels:
    app: management
spec:
  ports:
    - port: 80
      #targetPort: 3005
      name: management
  type: ClusterIP
  selector:
    app: management
