apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctrl-management
  namespace: ctrl-apps
  labels:
    app: management
spec:
  selector:
    matchLabels:
      app: management
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: management
    spec:
      containers:
        - name: management
          image: ghcr.io/sg-wireless/ctrl-management-dev:4.0.0
          # resources:
          #   requests:
          #     cpu: 200m
          #     memory: 200Mi
          #   limits:
          #     cpu: 200m
          #     memory: 200Mi
          ports:
          - containerPort: 80
            name: management
          # command: [ "sh", "-c", "--" ]
          # args: [ "while true; do sleep 30; done;" ]
          env:
            - name: NODE_ENV
              value: "development"
            - name: APP_ENV
              value: "development"
            - name: DOCKER_DEV
              value: "true"
      imagePullSecrets:
        - name: ghcr-login-secret
