- hosts: all
  tasks:
    - name: updating apt
      become: true
      become_user: root
      command: apt update

    - name: install needed packages
      become: true
      become_user: root
      apt:
        state: present
        name:
          - redis-tools
          - redis-server
          - redis
          - python3-pip
          - python3.9

    - name: copy redis configuration
      ansible.builtin.template:
        src: config/redis.conf
        dest: /etc/redis/redis.conf
        owner: redis
      become: true

    - name: restart redis service
      ansible.builtin.systemd:
        name: redis
        state: restarted
      become: true
      become_user: root

    - name: Enable redis at startup
      become: true
      become_user: root
      ansible.builtin.systemd:
        name: redis
        enabled: yes

    - name: install awscli
      command: pip install awscli
      become: true
      become_user: root

    - name: reset ssh connection to allow user changes to affect ansible user
      ansible.builtin.meta: reset_connection

    - name: Login to CodeArtifact
      ansible.builtin.command: aws --region=eu-central-1 codeartifact login --tool pip --repository pycom-pypi --domain pycom --domain-owner 815345548820
      become: true
      become_user: root

    - name: install service-monitoring
      command: pip install service-monitoring
      become: true
      become_user: root

    - name: Add "*bin" folders to cron PATH
      ansible.builtin.cron:
        name: PATH
        env: yes
        job: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    - name: run healthcheck every 5 minutes
      ansible.builtin.cron:
        name: "check-redis"
        minute: "*/5"
        hour: "*"
        job: "service-monitoring --service redis --port 6379 --tenant {{tenant}} --environment {{env}}"
