apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: ctrl-rabbitmq
  namespace: ctrl-apps
spec:
  terminationGracePeriodSeconds: 600
  persistence:
    storageClassName: gp2
    storage: 10Gi
  replicas: 1
  resources:
    requests:
      cpu: 300m
      memory: 300Mi
    limits:
      cpu: 300m
      memory: 300Mi
  rabbitmq:
    additionalConfig: |
      log.console.level = info
      channel_max = 1500
      default_user_tags.administrator = true
  service:
    type: ClusterIP
