apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: ctrl-apps
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  PGDATA: /var/lib/postgresql/data/pgdata

---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: postgres-volume-claim
#  namespace: ctrl-apps
#  labels:
#    app: postgres
#spec:
#  storageClassName: gp2
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 2Gi
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: ctrl-postgres
#  namespace: ctrl-apps
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: postgres
#  template:
#    metadata:
#      labels:
#        app: postgres
#    spec:
#      containers:
#        - name: postgres
#          image: 'postgres:14'
#          imagePullPolicy: IfNotPresent
#          ports:
#            - containerPort: 5432
#          envFrom:
#            - configMapRef:
#                name: postgres-secret
#          volumeMounts:
#            - mountPath: /var/lib/postgresql/data
#              name: postgresdata
#      volumes:
#        - name: postgresdata
#          persistentVolumeClaim:
#            claimName: postgres-volume-claim
#---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ctrl-postgres
  namespace: ctrl-apps
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        args: ["-c", "shared_buffers=2GB", "-c", "effective_cache_size=8GB", "-c", "work_mem=16MB", "-c", "maintenance_work_mem=410MB", "-c", "min_wal_size=2GB", "-c", "max_wal_size=3GB", "-c", "checkpoint_completion_target=0.9", "-c", "wal_buffers=-1", "-c", "listen_addresses=*", "-c", "max_connections=1000", "-c", "random_page_cost=1.1", "-c", "effective_io_concurrency=300", "-c", "max_worker_processes=40", "-c", "max_parallel_workers_per_gather=4", "-c", "max_parallel_workers=40"]
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-secret
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  serviceName: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: gp2
      volumeMode: Filesystem
      resources:
        requests:
          storage: 5Gi
